### ISSUE TITLE
Testing extension stops with exit code 55 and no error message

### ISSUE THREAD

**Issue by fpoli** [microsoft/vscode-test#77]
From time to time I observe that VSCode stops with exit code 55 when testing an extension on MacOS. The following output is from [the macos-latest job of thi GitHub action](https://github.com/viperproject/prusti-assistant/pull/6/checks?check_run_id=1285357320). This has never happened when testing on Ubuntu/Windows. Note also that within the same execution, two previous executions of `runTests(..)` worked fine.

```
(...)

Found .vscode-test/vscode-1.50.0. Skipping download.
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2020-10-21T07:26:36.272Z] update#setState idle

Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.

(node:2076) Electron: Loading non-context-aware native module in renderer: '/Users/runner/work/prusti-assistant/prusti-assistant/.vscode-test/vscode-1.50.0/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

2020-10-21 07:26:37.742 Code Helper (Renderer)[2076:15100] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

2020-10-21 07:26:37.742 Code Helper (Renderer)[2076:15100] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.

2020-10-21 07:26:37.750 Code Helper (Renderer)[2076:15100] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

(node:2076) Electron: Loading non-context-aware native module in renderer: '/Users/runner/work/prusti-assistant/prusti-assistant/.vscode-test/vscode-1.50.0/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

Exit code:   55
Done

Failed
Failed to run tests
npm ERR! Test failed.  See above for more details.
Error: The process '/Users/runner/hostedtoolcache/node/12.19.0/x64/bin/npm' failed with exit code 1
```

**Comment by connor4312** [comment]
This looks like it was fixed in your repo updating to 1.51 (https://github.com/viperproject/prusti-assistant/commit/61090a5c745ed99a238a825f318ba06e51026b52). Please let us know if it recurs.

**Comment by fpoli** [comment]
This is happening again, with `vscode-darwin-1.57.0`. Do you have any idea of what the cause might be?
```
2021-09-21T11:11:57.0107540Z Found /Users/runner/work/prusti-assistant/prusti-assistant/.vscode-test/vscode-darwin-1.57.0. Skipping download.
2021-09-21T11:11:57.4285290Z Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
2021-09-21T11:11:57.4331270Z 
2021-09-21T11:11:57.5707030Z [90m[main 2021-09-21T11:11:57.567Z][0m update#setState idle
2021-09-21T11:11:57.5808380Z 
2021-09-21T11:11:57.8019450Z Unable to create basic Accelerated OpenGL renderer.
2021-09-21T11:11:57.8120880Z 
2021-09-21T11:11:57.8221940Z Unable to create basic Accelerated OpenGL renderer.
2021-09-21T11:11:57.8323320Z 
2021-09-21T11:11:57.8425700Z Core Image is now using the software OpenGL renderer. This will be slow.
2021-09-21T11:11:57.8525410Z 
2021-09-21T11:11:58.9049470Z 2021-09-21 11:11:58.904 Code Helper (Renderer)[2720:21519] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-09-21T11:11:58.9059820Z 
2021-09-21T11:11:58.9150090Z 2021-09-21 11:11:58.904 Code Helper (Renderer)[2720:21519] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2021-09-21T11:11:58.9167580Z 
2021-09-21T11:11:58.9178530Z 2021-09-21 11:11:58.912 Code Helper (Renderer)[2720:21519] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-09-21T11:11:58.9220330Z 
2021-09-21T11:12:03.3643560Z (node:2869) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2021-09-21T11:12:03.3646320Z (Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
2021-09-21T11:12:03.3647200Z 
2021-09-21T11:12:03.5565070Z Exit code:   55
```

[The full output is here](https://github.com/microsoft/vscode-test/files/7202629/output.txt). (The PR in which this happened is https://github.com/viperproject/prusti-assistant/pull/99, but I'm going to force push to that.)

**Comment by fpoli** [comment]
I somehow avoided this error by doing unrelated changes to my test suite, but I believe the root issue is still unresolved.

**Comment by RedMickey** [comment]
Hi, I faced the similar issue on the `macOS-latest` image of Azure DevOps pipeline. Tests on `ubuntu-latest` and `windows-latest` images work without problems. I was able to fix this issue by specifying the latest stable version (`version: "stable"`) in test options. But if I specify some previous version (e.g. `1.62.3`), the tests will fail with the error on startup:
```
Extension host with pid 2940 exited with code: 55, signal: null.

Exit code:   55
```

<details>
<summary>Test logs</summary>

```
Starting: Run localization tests
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.189.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
npm run test-localization --verbose
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/fcc15520-b6c8-4357-9453-385e7aa1c159.sh
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/Users/runner/hostedtoolcache/node/14.18.2/x64/bin/node',
npm verb cli   '/Users/runner/hostedtoolcache/node/14.18.2/x64/bin/npm',
npm verb cli   'run',
npm verb cli   'test-localization',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.15
npm info using node@v14.18.2
npm verb run-script [
npm verb run-script   'pretest-localization',
npm verb run-script   'test-localization',
npm verb run-script   'posttest-localization'
npm verb run-script ]
npm info lifecycle vscode-react-native@1.8.1~pretest-localization: vscode-react-native@1.8.1
npm info lifecycle vscode-react-native@1.8.1~test-localization: vscode-react-native@1.8.1

> vscode-react-native@1.8.1 test-localization /Users/runner/work/1/s
> node ./test/localization/runTest.js

/Users/runner/work/1/s/test/localization/index
Found /Users/runner/work/1/s/.vscode-test/vscode-darwin-1.62.3. Skipping download.
[main 2021-12-10T09:21:35.620Z] update#setState idle

2021-12-10 09:21:37.699 Code Helper (Renderer)[2785:21588] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

2021-12-10 09:21:37.699 Code Helper (Renderer)[2785:21588] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.

2021-12-10 09:21:37.711 Code Helper (Renderer)[2785:21588] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

Starting extension host with pid 2940.

[LocalProcessExtensionHost]: IExtensionHostStarter.start() took 13 ms.

(node:2940) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)

Extension host with pid 2940 exited with code: 55, signal: null.

Exit code:   55
Done

Failed
Failed to run tests
npm verb lifecycle vscode-react-native@1.8.1~test-localization: unsafe-perm in lifecycle true
npm verb lifecycle vscode-react-native@1.8.1~test-localization: PATH: /Users/runner/hostedtoolcache/node/14.18.2/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/runner/work/1/s/node_modules/.bin:/Users/runner/hostedtoolcache/node/14.18.2/x64/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
npm verb lifecycle vscode-react-native@1.8.1~test-localization: CWD: /Users/runner/work/1/s
npm info lifecycle vscode-react-native@1.8.1~test-localization: Failed to exec test-localization script
npm verb stack Error: vscode-react-native@1.8.1 test-localization: `node ./test/localization/runTest.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/runner/hostedtoolcache/node/14.18.2/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:400:28)
npm verb stack     at ChildProcess.<anonymous> (/Users/runner/hostedtoolcache/node/14.18.2/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm verb pkgid vscode-react-native@1.8.1
npm verb cwd /Users/runner/work/1/s
npm verb Darwin 20.6.0
npm verb argv "/Users/runner/hostedtoolcache/node/14.18.2/x64/bin/node" "/Users/runner/hostedtoolcache/node/14.18.2/x64/bin/npm" "run" "test-localization" "--verbose"
npm verb node v14.18.2
npm verb npm  v6.14.15
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-react-native@1.8.1 test-localization: `node ./test/localization/runTest.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-react-native@1.8.1 test-localization script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 9744ms
```
</details>
